name = "ddproxy"
main = "index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Environment variables will be managed via wrangler secrets
# Use: wrangler secret put VARIABLE_NAME

# Enable observability for debugging
[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

# Worker will be available at ddproxy.rustaml.workers.dev automatically

[env.staging]
# Staging environment for local development
# Environment variables will be loaded from .env.staging