name = "ddproxy"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Environment variables (populated from .env file)
[vars]
ENVIRONMENT = "${WORKER_ENVIRONMENT}"
DD_FORWARD_ENABLED = "${DD_FORWARD_ENABLED}"
OTEL_COLLECTOR_ENDPOINT = "${OTEL_COLLECTOR_ENDPOINT}"
OTEL_COLLECTOR_AUTH = "${OTEL_COLLECTOR_AUTH}"

# Enable observability for debugging
[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

# Worker will be available at ddproxy.rustaml.workers.dev automatically