version: '3.8'

services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "8126:8126"   # DataDog receiver (primary port for DDTrace)
    volumes:
      - ../generated/otel-config.yaml:/etc/otelcol-contrib/otel-config.yaml
    command: ["--config=/etc/otelcol-contrib/otel-config.yaml"]
    restart: unless-stopped

  # DDTrace Application
  ddtrace-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ddtrace-app
    depends_on:
      - otel-collector
    environment:
      # DDTrace configuration - sends to localhost:8126 by default
      - DD_SERVICE=ddtrace-webapp
      - DD_ENV=demo
      - DD_VERSION=1.0.0
      # Point DDTrace to the collector container
      - DD_AGENT_HOST=otel-collector
      - DD_TRACE_AGENT_PORT=8126
    volumes:
      - ../generated/.env:/app/.env
    command: >
      ddtrace-run python ddtrace_app.py 
      --requests 100 
      --workers 3 
      --interval 500ms 
      --users 25